<?php
    /**
     * Created by PhpStorm.
     * 版权所有: 2019~2022 [ hhygyl ]
     * Date: 2019/8/20-16:10
     * Link: http://luckyadmin.luckyhhy.cn
     * FileName: Advice.php
     * Keys: ctrl+alt+L/ctrl+s(代码格式化) ctrl+J(代码提示) ctrl+R(替换)ALT+INSERT(生成代码(如GET,SET方法,构造函数等) , 光标在类中才生效)
     * CTRL+ALT+O (优化导入的类和包 需要配置) SHIFT+F2(高亮错误或警告快速定位错误)
     * CTRL+SHIFT+Z(代码向前) CTRL+SHIFT+/ (块状注释) ctrl+shift+enter(智能完善代码 如if())
     **************************************************************
     *                                                            *
     *   .=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-.       *
     *    |                     ______                     |      *
     *    |                  .-"      "-.                  |      *
     *    |                 /            \                 |      *
     *    |     _          |              |          _     |      *
     *    |    ( \         |,  .-.  .-.  ,|         / )    |      *
     *    |     > "=._     | )(__/  \__)( |     _.=" <     |      *
     *    |    (_/"=._"=._ |/     /\     \| _.="_.="\_)    |      *
     *    |           "=._"(_     ^^     _)"_.="           |      *
     *    |               "=\__|IIIIII|__/="               |      *
     *    |              _.="| \IIIIII/ |"=._              |      *
     *    |    _     _.="_.="\          /"=._"=._     _    |      *
     *    |   ( \_.="_.="     `--------`     "=._"=._/ )   |      *
     *    |    > _.="                            "=._ <    |      *
     *    |   (_/                                    \_)   |      *
     *    |                                                |      *
     *    '-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-='      *
     *                                                            *
     *                    JUST FIND YOUR BUG !                    *
     **************************************************************
     */


    namespace app\admin\controller;


    use think\Exception;

    class Advice extends SystemBase
    {

        protected $advice;
        protected function _initialize()
        {
            parent::_initialize(); // TODO: Change the autogenerated stub

            $this->advice=new \app\admin\model\Advice();
        }


        /**
         * @return mixed
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: index
         * @describe:
         */
        public function index(){
            if($this->request->isAjax()){
                $param=$this->request->param();

                return $this->advice->GetAdminAdviceDataPage($param);
            }
            return $this->fetch();
        }



        /**
         * @return mixed
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: AddAdvice
         * @describe:添加广告
         */
        public function AddAdvice(){
            if($this->request->isAjax()){
                $data=$this->request->post();
               // dump($data);
                $res=$this->advice->addEditData($data);
                if($res['code']==1) {
                    if(isset($data['id'])){
                        $this->AddLogs('编辑广告【'.$data['name'].'】信息');
                    }else{
                        $this->AddLogs('添加广告【'.$data['name'].'】');
                    }
                    $this->success("操作成功");
                }
                else {
                    $this->error($res['msg']);
                }
            }
            return $this->fetch();
        }


        /**
         * @return mixed
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: EditAdvice
         * @describe:编辑广告
         */
        public function EditAdvice()
        {
            $id   = $this->request->param("id/d");//父id
            $info = $this->advice->get($id)->toArray();

            $this->assign(compact("info"));
            return $this->fetch();
        }


        /**
         * @author: hhygyl <hhygyl520@qq.com>
         * @name: delete
         * @describe:删除
         */
        public function delete()
        {
            if($this->request->isAjax()) {
                $ids = $this->request->post("ids");
                try {
                    $res = $this->advice->del($ids); //模型删除
                    if($res) {
                        $this->AddLogs('删除广告');

                        $this->success("删除成功");
                    }
                    else {
                        $this->error("删除失败");
                    }
                } catch (Exception $exception) {
                    $this->error($exception->getMessage());
                }
            }
        }


    }