<?php
    /**
     * Created by PhpStorm.
     * 版权所有: 2019~2022 [ hhygyl ]
     * Date: 2019/8/23-13:04
     * Link: http://luckyadmin.luckyhhy.cn
     * FileName: Password.php
     * Keys: ctrl+alt+L/ctrl+s(代码格式化) ctrl+J(代码提示) ctrl+R(替换)ALT+INSERT(生成代码(如GET,SET方法,构造函数等) , 光标在类中才生效)
     * CTRL+ALT+O (优化导入的类和包 需要配置) SHIFT+F2(高亮错误或警告快速定位错误)
     * CTRL+SHIFT+Z(代码向前) CTRL+SHIFT+/ (块状注释) ctrl+shift+enter(智能完善代码 如if())
     **************************************************************
     *                                                            *
     *   .=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-.       *
     *    |                     ______                     |      *
     *    |                  .-"      "-.                  |      *
     *    |                 /            \                 |      *
     *    |     _          |              |          _     |      *
     *    |    ( \         |,  .-.  .-.  ,|         / )    |      *
     *    |     > "=._     | )(__/  \__)( |     _.=" <     |      *
     *    |    (_/"=._"=._ |/     /\     \| _.="_.="\_)    |      *
     *    |           "=._"(_     ^^     _)"_.="           |      *
     *    |               "=\__|IIIIII|__/="               |      *
     *    |              _.="| \IIIIII/ |"=._              |      *
     *    |    _     _.="_.="\          /"=._"=._     _    |      *
     *    |   ( \_.="_.="     `--------`     "=._"=._/ )   |      *
     *    |    > _.="                            "=._ <    |      *
     *    |   (_/                                    \_)   |      *
     *    |                                                |      *
     *    '-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-='      *
     *                                                            *
     *                    JUST FIND YOUR BUG !                    *
     **************************************************************
     */


    namespace app\admin\controller;


    use service\UtilService;
    use think\Exception;

    class Password extends SystemBase
    {


        protected  $password;
        protected function _initialize()
        {
            parent::_initialize(); // TODO: Change the autogenerated stub
            $this->password=new \app\admin\model\Password();
        }


        /**
         * @return mixed
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: index
         * @describe:数据展示页
         */
        public function index(){

            if($this->request->isAjax()){
                $param=$this->request->param();
                return $this->password->GetPasswordDataPage($param);
            }

            return $this->fetch();
        }



        /**
         * @return mixed
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: AddAccount
         * @describe:添加和编辑
         */
        public function AddAccount(){

            if($this->request->isAjax()){
                $data=$this->request->post();

                if(!empty($data['url'])){
                    $ok=UtilService::is_url($data['url']);
                    if(!$ok){
                        $this->error("填写的url 地址有误");
                    }
                }
                $res=$this->password->addEditData($data);
                if($res['code']==1){
                    $this->success("操作成功");
                }else{
                    $this->error($res['msg']);
                }
            }
            return $this->fetch();
        }


        /**
         * @return mixed
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: EditAccount
         * @describe:编辑
         */
        public function EditAccount(){
            $id=$this->request->param("id/d",0,"intval");
            $info=$this->password->get($id)->toArray();
            if(!$info){
                $this->error("数据未找到");
            }
            $this->assign(compact("info"));
            return $this->fetch();
        }


        /**
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: delete
         * @describe:删除
         */
        public function delete()
        {
            if($this->request->isAjax()) {
                $ids = $this->request->post("ids");
                try {
                    $res = $this->password->del($ids); //模型删除
                    if($res) {
                        $this->success("删除成功");
                    }
                    else {
                        $this->error("删除失败");
                    }
                } catch (Exception $exception) {
                    $this->error($exception->getMessage());
                }
            }
        }





    }