<?php
    /**
     * Created by PhpStorm.
     * 版权所有: 2019~2022 [ hhygyl ]
     * Date: 2019/7/24-16:19
     * Link: http://luckyadmin.luckyhhy.cn
     * FileName: Users.php
     * Keys: ctrl+alt+L/ctrl+s(代码格式化) ctrl+J(代码提示) ctrl+R(替换)ALT+INSERT(生成代码(如GET,SET方法,构造函数等) , 光标在类中才生效)
     * CTRL+ALT+O (优化导入的类和包 需要配置) SHIFT+F2(高亮错误或警告快速定位错误)
     * CTRL+SHIFT+Z(代码向前) CTRL+SHIFT+/ (块状注释) ctrl+shift+enter(智能完善代码 如if())
     *
     **************************************************************
     *                                                            *
     *   .=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-.       *
     *    |                     ______                     |      *
     *    |                  .-"      "-.                  |      *
     *    |                 /            \                 |      *
     *    |     _          |              |          _     |      *
     *    |    ( \         |,  .-.  .-.  ,|         / )    |      *
     *    |     > "=._     | )(__/  \__)( |     _.=" <     |      *
     *    |    (_/"=._"=._ |/     /\     \| _.="_.="\_)    |      *
     *    |           "=._"(_     ^^     _)"_.="           |      *
     *    |               "=\__|IIIIII|__/="               |      *
     *    |              _.="| \IIIIII/ |"=._              |      *
     *    |    _     _.="_.="\          /"=._"=._     _    |      *
     *    |   ( \_.="_.="     `--------`     "=._"=._/ )   |      *
     *    |    > _.="                            "=._ <    |      *
     *    |   (_/                                    \_)   |      *
     *    |                                                |      *
     *    '-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-='      *
     *                                                            *
     *                    JUST FIND YOUR BUG !                    *
     **************************************************************
     */

    namespace app\admin\controller;

    use think\Exception;

    class Users extends SystemBase
    {
        protected $users;
        protected function _initialize()
        {
            parent::_initialize(); // TODO: Change the autogenerated stub
            $this->users=new \app\admin\model\Users();
        }


        public function index(){
            if($this->request->isAjax()) {
                $param = $this->request->param();//接收参数
                /**
                 * 返回获取的分页数据
                 */
                return $this->users->GetUsersDataPage($param);
            }
            return $this->fetch();

        }


        /**
         * @return mixed
         * @author: hhygyl <hhygyl520@qq.com>
         * @name: EditUsers
         * @describe:编辑会员信息
         */
        public function EditUsers(){

            if($this->request->isAjax()) {
                $data = $this->request->post();
                try {
                    $res = $this->users->editData($data);
                    if($res!==false) {
                        $this->AddLogs('编辑用户信息【'.$data['username'].'】');
                        $this->success("提交成功");
                    }
                    else {
                        $this->error("提交失败");
                    }
                } catch (Exception $exception) {
                    $this->error($exception->getMessage());
                }
            }
            $id=$this->request->param("id/d");
            $info=$this->users->get($id);
            $this->assign("info",$info);
            return $this->fetch();
        }



        /**
         * @author: hhygyl <hhygyl520@qq.com>
         * @name: delete
         * @describe:删除
         */
        public function delete()
        {
            if($this->request->isAjax()) {
                $ids = $this->request->post("ids");
                return $this->DeleteData("users",$ids);
            }
        }


    }