<?php
    /**
     * Created by PhpStorm.
     * 版权所有: 2019~2022 [ hhygyl ]
     * Date: 2019/8/15-14:33
     * Link: http://luckyadmin.luckyhhy.cn
     * FileName: Album.php
     * Keys: ctrl+alt+L/ctrl+s(代码格式化) ctrl+J(代码提示) ctrl+R(替换)ALT+INSERT(生成代码(如GET,SET方法,构造函数等) , 光标在类中才生效)
     * CTRL+ALT+O (优化导入的类和包 需要配置) SHIFT+F2(高亮错误或警告快速定位错误)
     * CTRL+SHIFT+Z(代码向前) CTRL+SHIFT+/ (块状注释) ctrl+shift+enter(智能完善代码 如if())
     **************************************************************
     *                                                            *
     *   .=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-.       *
     *    |                     ______                     |      *
     *    |                  .-"      "-.                  |      *
     *    |                 /            \                 |      *
     *    |     _          |              |          _     |      *
     *    |    ( \         |,  .-.  .-.  ,|         / )    |      *
     *    |     > "=._     | )(__/  \__)( |     _.=" <     |      *
     *    |    (_/"=._"=._ |/     /\     \| _.="_.="\_)    |      *
     *    |           "=._"(_     ^^     _)"_.="           |      *
     *    |               "=\__|IIIIII|__/="               |      *
     *    |              _.="| \IIIIII/ |"=._              |      *
     *    |    _     _.="_.="\          /"=._"=._     _    |      *
     *    |   ( \_.="_.="     `--------`     "=._"=._/ )   |      *
     *    |    > _.="                            "=._ <    |      *
     *    |   (_/                                    \_)   |      *
     *    |                                                |      *
     *    '-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-='      *
     *                                                            *
     *                    JUST FIND YOUR BUG !                    *
     **************************************************************
     */


    namespace app\index\controller;


    use app\admin\model\AlbumImages;
    use service\UtilService;
    use think\Cache;
    use think\Exception;

    class Album extends Base
    {
        protected function _initialize()
        {
            parent::_initialize(); // TODO: Change the autogenerated stub
        }



        /**
         * @return mixed
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: lists
         * @describe:相册列表
         */
        public function lists(){
             if(empty($this->navigate_id) || $this->navigate_id==0){
                 $this->redirect("lucky/notfound");
             }
             $data=model("admin/Album")->indedxAlbum(); //列表数据
             $page=$data->render();
             $this->assign('datas',$data);
             $this->assign('page',$page);

            return $this->fetch();
        }


        /**
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: zan
         * @describe:图片点赞
         */
        public function zan(){
            if($this->request->isAjax()){
                $id=$this->request->post("id");
                $this->all_zan("album","hits",$id);
            }
        }


        /**
         * @throws \think\db\exception\DataNotFoundException
         * @throws \think\db\exception\ModelNotFoundException
         * @throws \think\exception\DbException
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: album_pass
         * @describe:相册解密
         */
        public function album_pass(){
            if($this->request->isPost()){
                $data=$this->request->post();
                $info=db("album")->find((int)$data['id']);
                if(!$info){
                    $this->error("网络错误！");
                }
                //dump($data['pass']);
                //dump(UtilService::think_encrypt("123456"));

                if($data['pass']!=UtilService::think_decrypt($info['password'])){
                    $this->error("密码错误");
                }
                $this->success("解密成功");
            }
        }


        /**
         * @return mixed
         * @throws \think\exception\DbException
         * @author: hhygyl <jackhhy520@qq.com>
         * @name: view_image
         * @describe:查看相册图片
         */
        public function view_image(){
            $id=$this->request->param("id/d",0,"intval");
            if(empty($id) || $id==0){
                $this->error("网络错误哟");
            }
            $data=db("album_images")->where("album_id",$id)->select();
           // dump($data);
            $this->assign("data",$data);
            return $this->fetch();
        }




    }